### ISSUE TITLE
[Suggestion] Add option for Dimensions

### ISSUE THREAD

**Issue by davqvist** [coolsquid/ToxicRain#1]
Forge 2460
MC 1.12.1
TR 1.0.0

Would it be possible to add an option to blacklist or whitelist dimensions for toxic rain?

**Comment by coolsquid** [comment]
Done. You can get the updated version [here](https://github.com/coolsquid/ToxicRain/releases/tag/v1.0.1) or [here](https://minecraft.curseforge.com/projects/toxicrain/files/2470681) (might take a while, Curse can be slow).

**Comment by davqvist** [comment]
Thanks a lot, will test soon.
