### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by BTRBT** [coolsquid/ToxicRain#2]
This happens often: https://i.imgur.com/yFAsHIe.png. I'm using Minecraft 1.12.2, latest version of forge, latest version of Toxic Rain, at the time of this posting. No other mods are installed.

**Comment by coolsquid** [comment]
I'll take a look when I have the time. In the meantime, you'll have to live with it or disable the rain coloring (set the "rainColor" config option to an empty string).
